name: nerve
description: A Flutter application.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_segmented_tab_control: ^1.0.1
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  syncfusion_flutter_pdfviewer: ^20.4.41
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.16
  file_picker: ^5.2.5
  provider: ^6.0.5
  firebase_storage: ^11.0.10
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  numberpicker: ^2.1.1
  shimmer: ^2.0.0
  firebase_messaging: ^14.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/gif/

