// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnA-aKS18uhAJK8Wi8phuTGf_tfq90ktE',
    appId: '1:783845818183:web:c2985b3578db929b2c9662',
    messagingSenderId: '783845818183',
    projectId: 'nerve-io',
    authDomain: 'nerve-io.firebaseapp.com',
    storageBucket: 'nerve-io.appspot.com',
    measurementId: 'G-2RGXV7HT9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAni16BApLiyfkyNkQI943m5u0_rawOCmg',
    appId: '1:783845818183:android:a205b86bcf85ce662c9662',
    messagingSenderId: '783845818183',
    projectId: 'nerve-io',
    storageBucket: 'nerve-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ0PpCV5myBsZnlr6yrGCM053-UeAB2qY',
    appId: '1:783845818183:ios:54a394eec5c948e02c9662',
    messagingSenderId: '783845818183',
    projectId: 'nerve-io',
    storageBucket: 'nerve-io.appspot.com',
    iosClientId: '783845818183-c70aola19q9ipbc1l4rj5kttk0ajt3rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.nerve',
  );
}
